# Generated by Django 4.2.7 on 2023-11-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_productinfo_options_alter_order_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='filename',
            field=models.FileField(blank=True, null=True, upload_to='service_ogs/data/', verbose_name='Файл с данными'),
        ),
    ]
