# Generated by Django 4.2.7 on 2023-11-15 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_shop_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='shop',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_infos', to='order.shop', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='filename',
            field=models.FileField(blank=True, null=True, upload_to='shop/', verbose_name='Файл с данными'),
        ),
    ]
